spring:
  application:
    name: 4-SSE-Chatroom

  datasource:
    url: jdbc:h2:mem:chatroom
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        auto_quote_keyword: true
    show-sql: true

