spring:
  application:
    name: 5-RabbitMQ-Chatroom

  datasource:
    url: jdbc:postgresql://localhost:5432/messaging
    username: messaging
    password: password

  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        auto_quote_keyword: true
    show-sql: true

